name: core_feature
description: "A new Flutter package project."
version: 0.0.1+1
homepage:

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
